services:

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Stockholm
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - ./config/db/db-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - db_data:/var/lib/mysql
    restart: unless-stopped

  api-service-notifier:
    image: ghcr.io/public-service-as-a-service/api-service-notifier:latest
    depends_on:
      db:
        condition: service_healthy
      api-service-sms-sender:
        condition: service_started
      api-service-teams-sender:
        condition: service_started
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/application.yml
    env_file: config/backend/.env-notifier
    volumes:
      - ./config/backend/application-notifier.yml:/app/config/application.yml
    restart: unless-stopped

  api-service-webappusers:
    image: ghcr.io/public-service-as-a-service/api-service-webappusers:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/application.yml
    env_file: config/backend/.env-webappusers
    volumes:
      - ./config/backend/application-webappusers.yml:/app/config/application.yml
    restart: unless-stopped

  api-service-sms-sender:
    image: ghcr.io/sundsvallskommun/api-service-sms-sender:latest
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/application.yml
    env_file: config/backend/.env-smssender
    volumes:
      - ./config/backend/application-smssender.yml:/app/config/application.yml
    restart: unless-stopped

  api-service-teams-sender:
    image: ghcr.io/public-service-as-a-service/api-service-teams-sender:latest
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/application.yml
    env_file: config/backend/.env-teams-sender
    volumes:
      - ./config/backend/application-teams-sender.yml:/app/config/application.yml
    restart: unless-stopped

  csv-filereader:
    image: ghcr.io/public-service-as-a-service/csv-filereader:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/app/config/application.yml
    env_file: config/backend/.env-csv-filereader
    volumes:
      - ./config/backend/application-csv-filereader.yml:/app/config/application.yml
      - /data/incoming:/data/incoming
      - /data/processed:/data/processed
      - /data/failed:/data/failed
      - /data/temp:/data/temp
    restart: unless-stopped

  web-app-nidhogg:
    image: ghcr.io/public-service-as-a-service/web-app-nidhogg:latest
    depends_on:
      - api-service-notifier
      - api-service-webappusers
      - api-service-teams-sender
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data: