logging:
  level:
    root: INFO

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: teamssender
  datasource:
    url: ${ENV_DB_URL}
    username: ${ENV_DB_USERNAME}
    password: ${ENV_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
azure:
  ad:
    2281:
      user: ${AZURE_USER}
      client-id: ${AZURE_CLIENT_ID}
      tenant-id: ${AZURE_TENANT_ID}
      redirect-uri: ${AZURE_REDIRECT_URI}
      scopes: ${AZURE_SCOPES}
      authority-url: ${AZURE_AUTHORITY_URL}
      client-secret: ${AZURE_CLIENT_SECRET}
      login-url: ${AZURE_LOGIN_URL}
graph:
  base-url: ${GRAPH_URL}
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'